version: '3'
services:
  php:
    container_name: demo-php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./public:/var/www/html
    networks:
      - internal
  nginx:
    container_name: demo-nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./docker/nginx/static:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8000:80'
    networks:
      - internal
networks:
  internal:
    driver: bridge
